# fly.toml app configuration file generated for autumn-field-8684 on 2023-06-29T03:27:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-field-8684"
primary_region = "ewr"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "3001" # add this

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3001
  processes = ["app"]